#!/bin/bash
# Build the basic user install test
# Syntax: $0 testName  where testName is one of the files in the tests folder, without the .sh at the end.

genericName="experiment"
testName="$1"
testFileName="$testName.sh"

# Include the run library
. runLib.sh

if ! [ -e tests/"$testFileName" ]; then
	echo "Could not find tests/$testFileName." >&2
	echo "Syntax: run testName" >&2
	echo "" >&2
	echo "Possible tests are" >&2
	listTests | indent >&2
	exit 1
fi

docker build -t "$genericName" .
docker run -v ../..:/var/achelRepos/achel -it "$genericName" "/var/tests/$testFileName"
