#!/bin/bash
# Run all tests and then print a summary at the end. No Args.

# Include the run library
. runLib.sh

report="/tmp/achelDockerTestResults"
finalResult=0

reportLine "Test name" "Value" "Item result" > "$report"

for testName in `listTestsWithoutDebug`; do
	./run $testName
	returnedValue=$?
	
	case $returnedValue in
		0)
			itemResult="Success"
		;;
		1)
			itemResult="Failure"
			finalResult=1
		;;
		*)
			itemResult="Other"
		;;
	esac
	
	reportLine "$testName" "$returnedValue" "$itemResult" >> "$report"
done

if [ "$finalResult" == 0 ]; then
	finalResultTest="Success"
else
	finalResultTest="Failure"
fi

echo >> "$report"
reportLine "Final result" "$finalResult" "$finalResultTest">> "$report"


echo
cat "$report"

exit $finalResult
