#!/bin/bash

countOfStuff=`ls /usr/achelData | wc -l`

if [ -e /usr/externalData/.achel ]; then
  cd /etc/achel
  echo "### Dev mode. Using host config. ###"
  ln -sfv /usr/externalData/.achel/{data,config} .
elif [ $countOfStuff -eq 0 ]; then
  # Unpack the backup for first time use.
  cd /usr/achelData
  tar -xjf /usr/backups/achelData.tar.bz2
fi

if [ "$COMMAND" == '' ]; then
  echo "Doesn't appear to have been called with the wrapper from automation/build...?" >&2
  exit 1
fi

cd /current
exec $COMMAND "$@"
