#!/bin/bash
# Description
#   Create a bug report that can be filed with the appropriate repo. Eg https://github.com/ksandom/achel/issues
#
# Syntax:
#   $0 profileName
#     profileName is the name of the profile to clear the cache from.
#
# Examples:
#   Creates a bug report for the doneIt app.
#     $0 doneIt

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. $libDir/bug.sh
. $libDir/packages.sh


profileName="$1"

creatBugReport "$profileName"
