#!/bin/bash
# Description
#   Build cache for an Achel application.
#
# Syntax:
#   $0 profileName
#     profileName is the name of the profile to remove the cache from.
#
# Examples:
#   Builds the cache for the doneIt application
#     $0 doneIt

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. $libDir/cache.sh
. $libDir/packages.sh


profileName="$1"

clearCache "$profileName"
