#!/bin/bash
# Description
#   Set where dropbox is located. Leaving it blank will make it default to ~/Dropbox.
#   This is tested with dropbox, but could easily be used with services like google drive.
#
# Syntax:
#   $0 [pathToDropbox]
#     pathToDropbox is the path where dropbox replicates. If you leave it blank, achel will try to figure it out.
#
# Examples:
#   Tells Achel that dropbox relicates to Dropbox.work in the current user's home directory.
#     $0 ~/Dropbox.work
#   
#   Tells Achel that dropbox relicates to Dropbox in the current user's home directory.

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/dropbox.sh

setDropboxHome "$1"
