#!/bin/bash
# Description
#   Remove a file from being replicated by a replication provider. This does not remove the file.
#   It simply makes the file local again, and leaves the destination file in place since I can't
#   assume how other users should be affected in your situation. If you know that you don't need
#   it, you can easily remove it yourself.
#
# Syntax:
#   $0 fileToRemove
#     fileToRemove is the file that should no longer be replicated. This can be found with fileRepFileList.
#
# Examples:
#   Tells Achel to no longer replicate the fileReplication settings.
#     $0 FileReplication.data.json
#   
#   Tells Achel to no longer replicate the fileReplication settings.
#     $0 DoneIt.data.json

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/fileReplication.sh
. "$libDir"/collection.sh

fileRepRemoveFile "$1"

