#!/bin/bash
# Description
#   Attempt to figure out how file replication is setup on the current machine and configure the Achel file replication accordingly. This assumes you already have something like dropbox already installed and configured.
#
# Syntax:
#   $0
#
# Examples:
#   Detect and configure fileReplication.
#     $0

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/fileReplication.sh
. "$libDir"/collection.sh

autoSetupReplicators

