#!/bin/bash
# Description
#   Lists out available packages.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the available packages.
#     $0
#   Lists the available packages and guarantees that there is no symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh
. $libDir/packages.sh

while read repo; do
	while read package;do 
		echo $repo	$package
	done < <(listPackages "$repo")
	
done < <(listRepos)

