#!/bin/bash
# Description
#   Create a release. Ready to be pushed.
#
# Syntax:
#   $0
#
# Examples:
#   Create a release. Ready to be pushed.
#     $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh
. $libDir/tag.sh
. $libDir/repo.sh
. $libDir/repoParms.sh

tag=`generateTag`
. $libDir/git.sh
. $libDir/docker.sh

mustFindRepoRoot

# Create the release.
gitTag
