#!/bin/bash
# Description
#   Create and push a release.
#
# Syntax:
#   $0
#
# Examples:
#   Create and push a release.
#     $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh
. $libDir/tag.sh
. $libDir/repo.sh
. $libDir/repoParms.sh

tag=`generateTag`
. $libDir/git.sh
. $libDir/docker.sh

mustFindRepoRoot

# Create the release.
gitTag

# Push it.
gitPush
