#!/bin/bash
# Description
#   Lists out currently installed repos.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the current repos including any symlink infomation.
#     $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh
. $libDir/repoParms.sh
. $libDir/repoInstall.sh

if [ "`echo $* | grep '\--short'`" == '' ]; then
	short="false"
else
	short="true"
fi

case $1 in
	'--short')
		listRepos
	;;
	*)
		repos=`listRepos "$1"`
		
		echo "$repos" | while read name;do
			echo "$name"
			repoGetParms "$name"
			echo
		done
	;;
esac
