#!/bin/bash
# Description
#   Lists out available packages in a repo.
#
# Syntax:
#   $0 repoName
#     repoName is the name used to refer to the repository.
#
# Examples:
#   Lists the profiles including any symlink infomation.
#     $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. $libDir/packages.sh

listPackages "$1"