#!/bin/bash
# Description
#   Install/Update all syntax highlighting that we know how to do so far.
#
# Syntax:
#   $0 [legacy]
#
# Examples:
#   Install/Update all current syntax highlighting that we know how to do so far.
#     $0
#
#   Install/Update all legacy syntax highlighting that we know how to do so far.
#     $0

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/display.sh
. "$libDir"/syntaxHighlighting.sh

highlightingInstall "$1"
