#!/bin/bash
# Description
#   Uninstalls Achel and all the programs installed via it.
#
# Syntax:
#   $0 uninstallAchel
#
# Examples:
#   Uninstall.
#     $0

requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh
. $libDir/display.sh
. $libDir/filesystem.sh
. $libDir/cache.sh
. $libDir/repoInstall.sh
. $libDir/getRepo.sh
. $libDir/repoParms.sh
. $libDir/packages.sh
. $libDir/installLibs.sh
. $libDir/documentation.sh


# Warn the user about what they are getting themselves in for
cat $docsDir/repos/achel/overview/messages/install/uninstallAchel.md
waitSeconds 5

# Uninstall all achel provided applications
listRepos | grep -v '^achel$' | while read repoName;do
	uninstallRepo_removeBindings "$repoName"
	removeRepo "$repoName"
done


 # Remove achel executable
filename="achel"
removeFilesIfExisting ~/bin/$filename /usr/bin/$filename /usr/local/bin/$filename

 # Remove manageAchel executable
filename="manageAchel"
removeFilesIfExisting ~/bin/$filename /usr/bin/$filename /usr/local/bin/$filename

 # Remove achel home
removeDirectiesIfExisting ~/.achel /etc/achel "$configDir" "$storageDir"
