#!/bin/bash
# Description
#   Safely update achel then all of the repos.
#
#   It will do a reinstall of that repo afterwards to make sure that any structural changes are applied.
#
#   Note if you only do this on some repos, there is a chance that interdependancies will be missed. To be sure, do a reinstall of all 
#
# Syntax:
#   $0 [--thorough]
#
#   --thorough will clean each repo before updating each repo.
#


requiredParms="$0"
. `dirname $0`/libs/includeLibs.sh

# Stuff for repo management
. $libDir/repoInstall.sh
. $libDir/getRepo.sh
. $libDir/repoParms.sh
. $libDir/packages.sh
. $libDir/installLibs.sh
. $libDir/filesystem.sh
. $libDir/display.sh
. $libDir/documentation.sh

programName='achel'
installTypeComments=''


echo "Sorry, update is not yet safe to use."
exit 1


thorough="$1"
repos=`listRepos`

# Update achel
echo 'achel' | updateRepos

# Run through the install to make sure nothing is broken
chooseInstallSettings
detectOldSettings
checkParameters "$*" $0
doInstall
# exit 1

# Clean the other repos
if [ "$thorough" == '--thorough' ]; then
	echo "$repos"| cleanRepos
fi

# Update the other repos
echo "$repos"| updateRepos
