#!/usr/bin/php
<?php
# Achel application starter.
# Copyright (c) 2012, Kevin Sandom under the BSD License. See LICENSE for full details.
 
define('programName', '~%programName%~');
$description="A commandline tool/API for doing awesome stuff on many nodes of a cluster.";
$profile=programName;

define('configDir', '~%configDir%~');
define('docsDir', '~%docsDir%~');
define('storageDir', '~%storageDir%~');
define('installType', '~%installType%~');
define('binExec', '~%binExec%~');
define('repoDir', '~%repoDir%~');

include configDir.'/core.php';

# Early processing of -q
$verbosity=0;
if (isset($argv[1]))
{
	$firstArg=$argv[1];
	if ($firstArg=='-q' or $firstArg=='--quiet') $verbosity=-1;
	elseif ($firstArg=='--debugStartup') $verbosity=4;
}


# initiate core
$core=core::assert($verbosity);
$cacheDir=configDir.'/profiles/'.$profile.'/cache';
$core->set('General', 'EOL', "\n");
$core->set('General', 'configDir', configDir);
$core->set('General', 'cacheDir', $cacheDir);
$core->set('General', 'docsDir', docsDir);
$core->set('General', 'storageDir', storageDir);
$core->set('General', 'installType', installType);
$core->set('General', 'binExec', binExec);
$core->set('General', 'profile', $profile);
$core->set('General', 'repoDir', repoDir);
$core->set('General', 'hostsDir', storageDir.'/data/1LayerHosts');
$core->set('General', 'programName', programName);
$core->set('General', 'description', $description);
$core->set('General', 'delayProcessingArgs', true);
$core->set('General', 'exitCode', 0);

if (file_exists($cacheDir))
{
	$core->loadCache($cacheDir);
	$core->set('General', 'cache', 'true');
}
else
{
	$core->set('General', 'cache', 'false');
	$core->set('General', 'noCacheReason', 'Could not find '.$cacheDir.'.');
	$core->debug(0, "No cache found. A re-install may be required.");
}

include (configDir.'/interfaces/commandLine.php');
$core->setRef('CommandLine', 'arguments', $argv);
loadModules($core, configDir."/profiles/$profile/modules");
$core->callFeature("triggerEvent", "Achel,interfaceStartup");
$core->callFeature("registerForEvent", "Achel,finishLate,outNow");

# Make it happen!
$core->go();

# We're finished, return an exit code to the command line.
$exitCode=$core->get('General', 'exitCode');
if (is_numeric($exitCode))
{
	exit(intval($exitCode));
}

?>
